name: nixbuild.net
description: Run Nix builds on nixbuild.net
author: Rickard Nilsson

inputs:

  nixbuild_token:
    required: true
    description: |
      The private auth token used to access nixbuild.net.

      You should not add your private token directly to the workflow file but
      instead define a GitHub Secret for it, to avoid mistakenly sharing your
      token with others.

      Follow the instructions in the README of this action for instructions
      on how to create and configure your auth token.

      The token must have the permissions 'build:read', 'build:write',
      'store:read' and 'store:write'.

      See https://docs.nixbuild.net/access-control/ for more details on auth
      tokens and permissions.


  generate_summary_for:
    required: false
    default: ''
    description: |
      If set to 'job', a summary of all builds and their resource usage will be
      generated as a GitHub Actions step summary for the job that used
      nixbuild-action.

      If set to 'workflow', the summary will instead include builds from all
      jobs executed so far during the workflow run. A workflow summary makes
      most sense for the very last job in your workflow (since it can be
      incomplete otherwise).

      If set to '', no summary will be generated.

  oidc:
    required: false
    default: false
    description: |
      If enabled, nixbuild-action will automatically fetch an OIDC ID
      Token from GitHub and pass it on to nixbuild.net so that OIDC claims
      can be used when authoring Biscuit policies. If this setting is enabled,
      you must make sure your job has the 'id-token: write' permission enabled.

      If you want to use OIDC, but instead want fetch the token yourself, keep
      the 'oidc' setting off, but make sure you add the fetched token an
      environment variable named 'NIXBUILDNET_OIDC_ID_TOKEN' before
      installing nixbuild-action. The OIDC ID Token must have the audience
      'nixbuild.net'.

  settings:
    required: false
    default: ''
    description: |
      Set any nixbuild.net settings to be used for builds and requests against
      nixbuild.net. See https://docs.nixbuild.net/settings for available
      settings. You must have
      https://docs.nixbuild.net/settings/index.html#settings-from-ssh-env set
      to true (the default), otherwise the settings defined here will be
      ignored.
      Settings are defined by `<name> = <value>` pairs, one per line. An
      example: `max-cpu = 2` (see https://docs.nixbuild.net/settings/#max-cpu).

  tags:
    required: false
    default: ''
    description: |
      Set any nixbuild.net tags to be used for builds and requests against
      nixbuild.net. In addition to the tags defined here, `nixbuild-action` will
      also add a set of tags specific to the GitHub Actions workflow run.
      Tags are defined by `<name> = <value>` pairs, one per line.

  ssh_address:
    required: false
    default: 'eu.nixbuild.net'
    description: |
      If you are running a self-hosted nixbuild.net deployment you can set
      this option to the address of your SSH endpoint.

  ssh_port:
    required: false
    default: 22
    description: |
      If you are running a self-hosted nixbuild.net deployment you can set
      this option to the port of your SSH endpoint.

  ssh_public_host_key:
    required: false
    default: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPIQCZc54poJ8vqawd8TraNryQeJnvH1eLpIDgbiqymM'
    description: |
      If you are running a self-hosted nixbuild.net deployment you can set
      this option to the public host key of your SSH endpoint.

  http_api_host:
    required: false
    default: 'api.nixbuild.net'
    description: |
      If you are running a self-hosted nixbuild.net deployment you can set
      this option to the host address of your HTTP API endpoint.

  http_api_port:
    required: false
    default: 443
    description: |
      If you are running a self-hosted nixbuild.net deployment you can set
      this option to the port your HTTP API endpoint.

  http_api_scheme:
    required: false
    default: 'https'
    description: |
      If you are running a self-hosted nixbuild.net deployment you can set
      this option to the schema (http or https) of your HTTP API endpoint.

  http_api_subpath:
    required: false
    default: ''
    description: |
      If you are running a self-hosted nixbuild.net deployment you can set
      this option to the subpath of your HTTP API endpoint.

runs:
  using: 'node20'
  main: 'index.js'
  post: 'summary.js'

branding:
  icon: zap
  color: gray-dark
